package sln1.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import org.jetbrains.annotations.NotNull;

public class Sln1_ApplicationPlugin extends BaseApplicationPlugin {
  private final PluginId myId = PluginId.getId("sln1");

  public Sln1_ApplicationPlugin() {
  }

  @NotNull
  public PluginId getId() {
    return myId;
  }

  public void createGroups() {
    // actions w/o parameters
    addAction(new ShowExtensionContributors_Action());
    // groups
    addGroup(new ExtensionContributionGroup_ActionGroup(this));
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(ExtensionContributionGroup_ActionGroup.ID, "MPSHelpMenu", null);
  }
}
