package sln3.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.Extension;

public class Sln3ExtensionImplementation extends Extension.Default<String> {
  public Sln3ExtensionImplementation() {
    super("sln1.Sln1.Extension");
  }


  public String get() {
    return "Sln3 implements Sln1.Extension";
  }
}
