package sln2.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.Extension;

public class Sln2ExtensionImplementation extends Extension.Default<String> {
  public Sln2ExtensionImplementation() {
    super("sln1.Sln1.Extension");
  }


  public String get() {
    return "Sln2 implements Sln1.Extension";
  }
}
